name: Backend Test

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Run the Gradle test task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean test
