name: Frontend Test

on:
  push:
    branches:
      - development
  pull_request:

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: NPM clean install
        run: npm ci
      - name: NPM run test
        run: npm run test
